# File: /config/packages/van_leveling.yaml

sensor:
  # REST sensor to get both pitch and roll in one request
  - platform: rest
    name: "Van Level Data"
    resource: http://YOUR_IP_HERE/readings
    method: GET
    scan_interval: 1
    value_template: "{{ value_json.pitch }}"  # required, even if we only use attributes
    json_attributes:
      - pitch
      - roll
      - ver
    unit_of_measurement: "°"

template:
  # Template sensors for pitch and roll from attributes
  - sensor:
      # dummy sensor to allow placing text on lovelace picture cards
      - name: "Van Level Text"
        unique_id: van_level_text
        state: " "

      - name: "Van Level Version"
        unique_id: van_level_version
        state: "{{ state_attr('sensor.van_level_data', 'ver') | default('Unknown') }}"

      - name: "Van Level Pitch"
        unique_id: van_level_pitch
        unit_of_measurement: "°"
        state: "{{ state_attr('sensor.van_level_data', 'pitch') | float(0) | round(1) }}"

      - name: "Van Level Roll"
        unique_id: van_level_roll
        unit_of_measurement: "°"
        state: "{{ state_attr('sensor.van_level_data', 'roll') | float(0) | round(1) }}"

      - name: "Van Level Pitch Height"
        unique_id: van_level_pitch_height
        unit_of_measurement: '"'
        state: >
          {{ ((states('sensor.van_level_pitch') | float(0) | abs) * (3.14159265 / 180)) | tan * 148 | round(2) }}

      - name: "Van Level Roll Height"
        unique_id: van_level_roll_height
        unit_of_measurement: '"'
        state: >
          {{ ((states('sensor.van_level_roll') | float(0) | abs) * (3.14159265 / 180)) | tan * 68 | round(2) }}

      - name: "Van Level Left Front Lift"
        unique_id: van_level_left_front_lift
        unit_of_measurement: '"'
        state: >
          {% set fraction = 2 %}
          {% set pitch = states('sensor.van_level_pitch') | float(0) %}
          {% set roll = states('sensor.van_level_roll') | float(0) %}
          {% set pitch_height = ((pitch | abs) * (3.14159265 / 180)) | tan * 148 %}
          {% set roll_height = ((roll | abs) * (3.14159265 / 180)) | tan * 68 %}
          {% if pitch < 0 and roll < 0 %} 0
          {% elif pitch < 0 and roll >= 0 %} {{ ((roll_height * fraction) | round(0)) / fraction }}
          {% elif pitch >= 0 and roll < 0 %} {{ ((pitch_height * fraction) | round(0)) / fraction }}
          {% else %} {{ (((roll_height + pitch_height) * fraction) | round(0)) / fraction }}
          {% endif %}

      - name: "Van Level Right Front Lift"
        unique_id: van_level_right_front_lift
        unit_of_measurement: '"'
        state: >
          {% set fraction = 2 %}
          {% set pitch = states('sensor.van_level_pitch') | float(0) %}
          {% set roll = states('sensor.van_level_roll') | float(0) %}
          {% set pitch_height = ((pitch | abs) * (3.14159265 / 180)) | tan * 148 %}
          {% set roll_height = ((roll | abs) * (3.14159265 / 180)) | tan * 68 %}
          {% if pitch < 0 and roll < 0 %} {{ ((roll_height * fraction) | round(0)) / fraction }}
          {% elif pitch < 0 and roll >= 0 %} 0
          {% elif pitch >= 0 and roll < 0 %} {{ (((roll_height + pitch_height) * fraction) | round(0)) / fraction }}
          {% else %} {{ ((pitch_height * fraction) | round(0)) / fraction }}
          {% endif %}

      - name: "Van Level Right Rear Lift"
        unique_id: van_level_right_rear_lift
        unit_of_measurement: '"'
        state: >
          {% set fraction = 2 %}
          {% set pitch = states('sensor.van_level_pitch') | float(0) %}
          {% set roll = states('sensor.van_level_roll') | float(0) %}
          {% set pitch_height = ((pitch | abs) * (3.14159265 / 180)) | tan * 148 %}
          {% set roll_height = ((roll | abs) * (3.14159265 / 180)) | tan * 68 %}
          {% if pitch < 0 and roll < 0 %} {{ (((roll_height + pitch_height) * fraction) | round(0)) / fraction }}
          {% elif pitch < 0 and roll >= 0 %} {{ ((pitch_height * fraction) | round(0)) / fraction }}
          {% elif pitch >= 0 and roll < 0 %} {{ ((roll_height * fraction) | round(0)) / fraction }}
          {% else %} 0
          {% endif %}

      - name: "Van Level Left Rear Lift"
        unique_id: van_level_left_rear_lift
        unit_of_measurement: '"'
        state: >
          {% set fraction = 2 %}
          {% set pitch = states('sensor.van_level_pitch') | float(0) %}
          {% set roll = states('sensor.van_level_roll') | float(0) %}
          {% set pitch_height = ((pitch | abs) * (3.14159265 / 180)) | tan * 148 %}
          {% set roll_height = ((roll | abs) * (3.14159265 / 180)) | tan * 68 %}
          {% if pitch < 0 and roll < 0 %} {{ ((pitch_height * fraction) | round(0)) / fraction }}
          {% elif pitch < 0 and roll >= 0 %} {{ (((roll_height + pitch_height) * fraction) | round(0)) / fraction }}
          {% elif pitch >= 0 and roll < 0 %} 0
          {% else %} {{ ((roll_height * fraction) | round(0)) / fraction }}
          {% endif %}